added safe unmount

diff --git a/gearlock/usr/lib/gearlock/compat/flashablezip/convert b/gearlock/usr/lib/gearlock/compat/flashablezip/convert
--- a/gearlock/usr/lib/gearlock/compat/flashablezip/convert
+++ b/gearlock/usr/lib/gearlock/compat/flashablezip/convert
@@ -4,6 +4,8 @@ usage() {
 	echo
 }
 
+die() { echo "==> ERROR: $1" >&2 && exit "${2:-1}"; }
+
 while getopts "A:adpvh" opt; do
 	case "$opt" in
 	A) ARCH="$OPTARG" ;;
@@ -64,13 +66,15 @@ fi
 
 # TODO: check for module.prop (magisk module format) & system.img (if it's a rom)
 
-"$GEARLIB"/extract "$FILE" "$TMPDIR"
-
-if [ -e "$TMPDIR/module.prop" ]; then
+content=$(unzip -l "$FILE")
+if echo "$content" | grep -q module.prop; then
+	"$GEARLIB"/extract "$FILE" "$TMPDIR" module.prop
 	eval "$(sed -r "s/^([a-zA-Z0-9_]+[a-zA-Z0-9_-]*=)(.*)$/\1\"\2\"/g" "$TMPDIR/module.prop" | tr '\n' ' ')"
-else
-	echo
+elif echo "$content" | grep -Eq "system(|_[ab]).img"; then
+	die "'$FILE' is a ROM and not supported" 2
 fi
+
+"$GEARLIB"/extract "$FILE" "$TMPDIR"
 
 # TODO: simulate a magisk/ksu environment to install flashable zips
 
