remove gxp, add install non-magisk/ksu-module flashable zip

diff --git a/gearlock/usr/lib/gearlock/compat/flashablezip/convert b/gearlock/usr/lib/gearlock/compat/flashablezip/convert
--- a/gearlock/usr/lib/gearlock/compat/flashablezip/convert
+++ b/gearlock/usr/lib/gearlock/compat/flashablezip/convert
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-die() { echo "==> ERROR: $1" >&2 && exit "${2:-1}"; }
+die() { echo "==> ERROR: $1" >&2 && quit "${2:-1}"; }
+
+quit() {
+	rm -rf "$TMPDIR"
+	exit "$1"
+}
 
 usage() {
 	echo
@@ -68,12 +73,7 @@ fi
 
 : "${ARCH:="$(busybox arch)"}"
 
-if grep -q " ROOT=" /proc/cmdline 2>/dev/null; then
-	TMPDIR=$SRCDIR/tmp
-	[ -d "$TMPDIR" ] || mkdir -p "$TMPDIR"
-else
-	TMPDIR=/data/local/tmp
-fi
+TMPDIR=$(tmpdir)
 
 # FREESPACES and FREESPACE are different
 FREESPACES=($("$GEARLIB"/checkfree))
@@ -155,3 +155,4 @@ abuild -Ff
 
 cd "$CURRENT_DIR"
 
+quit 0
diff --git a/gearlock/usr/lib/gearlock/compat/flashablezip/install b/gearlock/usr/lib/gearlock/compat/flashablezip/install
--- a/gearlock/usr/lib/gearlock/compat/flashablezip/install
+++ b/gearlock/usr/lib/gearlock/compat/flashablezip/install
@@ -3,19 +3,33 @@
 # just need to run update-binary
 # and add to gqueue
 
+die() { echo "==> ERROR: $1" >&2 && quit "${2:-1}"; }
+
+quit() {
+	rm -rf "$TMPDIR"
+	exit "$1"
+}
+
+TMPDIR=$(tmpdir)
+BIN=/META-INF/com/google/android/update-binary
+"$GEARLIB/extract" "$1" "$TMPDIR" -f $BIN
 
 # TODO: simulate a magisk/ksu environment to install flashable zips
 
-if modinfo ksu 2>&1 >/dev/null && strings "$WORKDIR/META-INF/com/google/android/update-binary" | grep -iEq "^k(ernel)?su$"; then
+if modinfo ksu 2>&1 >/dev/null && strings "$TMPDIR/$BIN" | grep -iEq "^k(ernel)?su$"; then
 	ILIB=ksu
 else
 	ILIB=magisk
 fi
+
 # TODO: if ksu/magisk exists,install from cmdline. If not, then install itself
 
-if [ -f "/data/adb/$ILIB/$ILIB" ]; do
+
+if [ -f "/data/adb/$ILIB/$ILIB" ]; then
 	"/data/adb/$ILIB/$ILIB" --install-module "$1"
 else
 	. "$GEARLIB/compat/flashablezip/$ILIB/functions.sh"
-	"$GEARLIB/extract" "$1" "$TMPDIR"
+  "$TMPDIR/$BIN" "$1"
 fi
+
+quit 0
