fix mkinitfs stuffs

diff --git a/gearlock/usr/bin/mkinitfs b/gearlock/usr/bin/mkinitfs
--- a/gearlock/usr/bin/mkinitfs
+++ b/gearlock/usr/bin/mkinitfs
@@ -44,6 +44,7 @@ funcgrep() {
         }' "$2"
 }
 
+# shellcheck disable=SC2317
 all_modules() {
 	# Add modules to the initcpio, filtered by grep.
 	#   $@: filter arguments to grep
@@ -57,9 +58,9 @@ all_modules() {
 	done
 	shift $((OPTIND - 1))
 
-	# _d_kmoduledir is assigned in mkinitcpio
+	# kerneldir is assigned in mkinitcpio
 	# shellcheck disable=SC2154
-	while read -r -d '' mod; do
+	while read -r mod; do
 		((++count))
 
 		for f in "${modfilter[@]}"; do
@@ -68,8 +69,8 @@ all_modules() {
 
 		mod="${mod##*/}"
 		mod="${mod%.ko*}"
-		echo '%s\n' "${mod//-/_}"
-	done < <(find "$_d_kmoduledir" -name '*.ko*' -print0 2>/dev/null | grep -EZz "$@")
+		printf '%s\n' "${mod//-/_}"
+	done < <(find "$kerneldir" -name '*.ko*' 2>/dev/null | grep "$@")
 
 	((count))
 }
@@ -98,7 +99,7 @@ add_checked_modules() {
 	# _autodetect_cache is declared in mkinitcpio and assigned in install/autodetect
 	# shellcheck disable=SC2154
 	if ((${#_autodetect_cache[*]})); then
-		mapfile -t mods < <(all_modules "$@" | grep -xFf <(echo '%s\n' "${!_autodetect_cache[@]}"))
+		mapfile -t mods < <(all_modules "$@" | grep -xFf <(printf '%s\n' "${!_autodetect_cache[@]}"))
 	else
 		mapfile -t mods < <(all_modules "$@")
 	fi
@@ -343,7 +344,7 @@ add_runscript() {
 	local -a funcs
 
 	if ! script="$DATADIR/hooks/$hookname"; then
-		echo "runtime script for '%s' not found" "$hookname"
+		echo "runtime script for '$hookname' not found"
 		return
 	fi
 
@@ -389,7 +390,7 @@ add_binary() {
 			interpreter="${shebang##\#\!*([[:space:]])}"
 			# strip /usr/bin/env and warn if it is missing
 			if [[ "$interpreter" == '/usr/bin/env'* ]]; then
-				[[ -e "${tmpdir}/usr/bin/env" ]] || echo "Possibly missing '/usr/bin/env' for script: %s" "$binary"
+				[[ -e "${tmpdir}/usr/bin/env" ]] || echo "Possibly missing '/usr/bin/env' for script: $binary"
 				interpreter="${interpreter##'/usr/bin/env'+([[:space:]])}"
 			fi
 			# strip parameters
@@ -400,7 +401,7 @@ add_binary() {
 			elif [[ -e "${tmpdir}/${interpreter}" ]]; then
 				:
 			else
-				echo "Possibly missing '%s' for script: %s" "$interpreter" "$binary"
+				echo "Possibly missing '$interpreter' for script: $binary"
 			fi
 		fi
 		return 0
@@ -412,7 +413,7 @@ add_binary() {
 		if [[ "$line" =~ $regex ]]; then
 			sodep="${BASH_REMATCH[2]}"
 		elif [[ "$line" = *'not found' ]]; then
-			echo "binary dependency '%s' not found for ${line%% *}" "$1"
+			echo "binary dependency '$1' not found for ${line%% *}"
 			((++_builderrors))
 			continue
 		fi
@@ -509,12 +510,12 @@ run_build_hook() {
 	unset -f build
 	# shellcheck disable=SC1090
 	if ! . "$script"; then
-		echo 'Failed to read %s' "$script"
+		echo "Failed to read $script"
 		return 1
 	fi
 
 	if ! declare -f install_hook >/dev/null; then
-		echo "Hook '%s' has no install_hook function" "${script}"
+		echo "Hook '$script' has no install_hook function"
 		return 1
 	fi
 
@@ -656,7 +657,7 @@ find_module_from_symbol() {
 			if decomp_to_stdout "$mod" | grep -Eq "^($symbols)" &>/dev/null; then
 				mod=${mod##*/}
 				mod="${mod%.ko*}"
-				echo '%s\n' "${mod//-/_}"
+				printf '%s\n' "${mod//-/_}"
 			fi
 		done < <(find "$moduledir" -name '*.ko*' -print0 2>/dev/null)
 	done
@@ -731,9 +732,9 @@ initfs_cpscripts() {
 			# only add real modules (2 == builtin)
 			((_addedmodules["$mod"] == 1)) && add+=("$mod")
 		done
-		((${#add[*]})) && echo 'MODULES="%s"\n' "${add[*]}"
+		((${#add[*]})) && printf 'MODULES="%s"\n' "${add[*]}"
 
-		echo '%s="%s"\n' \
+		printf '%s="%s"\n' \
 			'EARLYHOOKS' "${_runhooks['early']# }" \
 			'HOOKS' "${_runhooks['hooks']# }" \
 			'LATEHOOKS' "${_runhooks['late']# }" \
diff --git a/gearlock/usr/share/gearlock/mkinitfs/init b/gearlock/usr/share/gearlock/mkinitfs/init
--- a/gearlock/usr/share/gearlock/mkinitfs/init
+++ b/gearlock/usr/share/gearlock/mkinitfs/init
@@ -1,4 +1,8 @@
-#!/bin/sh
+#!/bin/busybox sh
+
+# Spread out busybox symlinks and make them available without full path
+/bin/busybox --install -s
+export PATH=/usr/bin:/system/bin:/system/xbin
 
 # some helpers
 # ebegin() {
@@ -169,10 +173,6 @@ find_mnt() {
 # 	fi
 # }
 
-# Spread out busybox symlinks and make them available without full path
-/bin/busybox --install -s
-export PATH=/usr/bin:/system/bin:/system/xbin
-
 # auto installation
 # [ "$AUTO_INSTALL" ] && INSTALL=1
 
@@ -250,6 +250,12 @@ check_root() {
 	mount_dir() { mount --bind "$1" "$2"; }
 	fs_type() { blkid -o value -s TYPE "$1"; }
 
+	err() {
+		echo "Failed to mount $1 to $2!"
+		cd /
+		return 1
+	}
+
 	case "$SYSTEM" in
 	/dev/* | UUID=* | LABEL=*)
 		SYSTEM=$(find_mnt "$SYSTEM")
@@ -261,35 +267,36 @@ check_root() {
 			;;
 		*) mount -t "$SYSTEMFS" "$SYSTEM" android ;;
 		esac
-		[ $? != 0 ] || return 1
+		[ $? != 0 ] || err "$SYSTEM" android
 		SYSTEM_BLK=true
 		;;
 	esac
 
+	cd /android
 	case "$DATA" in
 	/dev/* | UUID=* | LABEL=*)
 		DATA=$(find_mnt "$DATA")
 		DATAFS=$(fs_type "$DATA")
-		mount -t "$DATAFS" "$DATA" data || return 1
+		mount -t "$DATAFS" "$DATA" data || err "$DATA" data
 		DATA_BLK=true
 		;;
 	9p)
 		modprobe 9pnet_virtio &&
 			mount -t 9p -o trans=virtio data data -oversion=9p2000.L,posixacl,cache=loose ||
-			return 1
+			err "$DATA" data
 		DATA_BLK=true
 		;;
 	esac
 
-	if [ ! "$DATA" ]; then
-		mount -t tmpfs tmpfs data
-		DATA_BLK=true
+	if [ "$SYSTEM_BLK" ]; then
+		if [ ! "$DATA" ]; then
+			mount -t tmpfs tmpfs data
+			cd /
+			DATA_BLK=true
+		fi
+		[ "$DATA_BLK" ] && return 0
 	fi
-
-	if [ "$SYSTEM_BLK" ] && [ "$DATA_BLK" ]; then
-		return 0
-	fi
-
+cd /
 	# [ "$ROOTFOUND" = "true" ] && return 0
 
 	MOUNT=mount
@@ -301,7 +308,7 @@ check_root() {
 	fi ;;
 	esac
 
-	$MOUNT ${FLAGS:+-o $FLAGS} ${FS:+-t $FS} "$device" /mnt || return 1
+	$MOUNT ${FLAGS:+-o $FLAGS} ${FS:+-t $FS} "$device" /mnt || err "$ROOT" /mnt
 
 	# if [ "$ISO" ] && [ -e "/mnt/$ISO" ]; then
 	# 	mount --move /mnt /iso
@@ -321,16 +328,18 @@ check_root() {
 
 	if [ $? != 0 ]; then
 		mountpoint -q /mnt && umount /mnt
-		return 1
+		err "$SYSTEM" android
 	fi
 
+	cd /android
 	DATA_IMG=/mnt/$SRC/$DATA
 	case "$DATA" in
 	*.img) mount_loop "$DATA_IMG" data ;;
 	data) mkdir -p "$DATA_IMG" && mount_dir "$DATA_IMG" data ;;
 	esac
 
-	[ $? = 0 ] || return 1
+	[ $? = 0 ] || err "$DATA" data
+	cd /
 }
 
 # if [ "$zfcp" ]; then
@@ -400,7 +409,7 @@ check_root() {
 # fi
 
 if [ -n "$earlymodules$MODULES" ]; then
-	modprobe -qab #${earlymodules//,/ } $MODULES
+	modprobe -qab ${earlymodules//,/ } $MODULES
 fi
 
 [ -z "$SRC" ] && [ "$BOOT_IMAGE" ] && SRC=$(dirname "$BOOT_IMAGE")
@@ -417,10 +426,10 @@ esac
 
 for dev in /dev/[hmnsv][dmrv][0-9a-z]* /dev/xvd[0-9a-z]* /dev/nvme[0-9]n[0-9]p[0-9a-z]* /dev/mmcblk[0-9]p[0-9a-z]*; do
 	[ -e "$dev" ] || continue
-	ln "$dev" /dev/block
+	ln "$dev" /dev/block/
 done
 
-export mount_handler=checkroot
+export mount_handler=check_root
 
 # load hooks
 run_hookfunctions "run_hook" $EARLYHOOKS
@@ -428,8 +437,10 @@ run_hookfunctions "run_hook" $EARLYHOOKS
 # ROOTFOUND=
 # if [ "$ROOT" ]; then
 # [ "$cryptroot" ] && nlplug-findfs $cryptopts -p /sbin/mdev ${debug_init:+-d} "$ROOT"
+
 "$mount_handler" "$(find_mnt "$ROOT")" ||
 	launch_shell "ERROR: Mount failed, quitting..."
+
 # else
 # 	echo -e "Detecting Android..."
 # 	for d in /dev/[hmnsv][dmrv][0-9a-z]* /dev/xvd[0-9a-z]* /dev/nvme[0-9]n[0-9]p[0-9a-z]* /dev/mmcblk[0-9]p[0-9a-z]*; do
