add gqueue tasks

diff --git a/gearlock/usr/bin/run-gqueue b/gearlock/usr/bin/run-gqueue
--- a/gearlock/usr/bin/run-gqueue
+++ b/gearlock/usr/bin/run-gqueue
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 quit() {
-	rm -rf /queue.glist
+	rm -rf /var/gearlock/queue.glist
 	exit "$1"
 }
 
@@ -17,30 +17,22 @@ run_task() {
 		NEWSIZE=$2
 		case "$(blkol TYPE "$DISK")" in
 		ext[234]) resize2fs "$DISK" "$NEWSIZE" ;;
-		xfs)
-			# echo "item = 2 or item = 3"
-			;;
-		fat)
-			# echo "item = 2 or item = 3"
-			;;
-		f2fs)
-			# echo "item = 2 or item = 3"
-			;;
-		*)
-			# echo "default (none of above)"
-			;;
+		xfs) ;; # TODO: read xfs blocksize and then calculate blocks and growfs
+		vfat) fatresize "$DISK" "$NEWSIZE" ;;
+		f2fs) ;; # TODO: calculate sectors and growfs
+		*) ;;
 		esac
 		[ $? = 0 ] || die "Failed to resize filesystem at $DISK"
 		;;
-	runcmd)
-		timeout 300 bash -c "eval $*" || die "Failed to run command $*"
-		;;
+	sysup) system-update "$*";;
+	runcmd) timeout 300 bash -c "eval $*" || die "Failed to run command $*" ;;
+	clean) find /gearroot -type f -iname "*-pending_remove" -exec rm -rf {} + ;;
 	*) die "task $cmd is not supported" ;;
 	esac
 }
 
 while IFS= read -r cmd; do
 	[ "$cmd" ] && run_task $cmd
-done </queue.glist
+done </var/gearlock/queue.glist
 
 quit 0
diff --git a/gearlock/usr/lib/gearlock/sysup/sysup_aonly b/gearlock/usr/lib/gearlock/sysup/sysup_aonly
--- a/gearlock/usr/lib/gearlock/sysup/sysup_aonly
+++ b/gearlock/usr/lib/gearlock/sysup/sysup_aonly
@@ -1,9 +1,6 @@
 #!/bin/bash
 
-die() {
-	echo "$*" >&2 &
-	exit 1
-}
+die() { echo "$*" >&2 && exit 1; }
 
 NEWIMG=$1
 NEWIMGSIZE=$(du -sk "$NEWIMG" | awk '{print $1}')
@@ -19,9 +16,11 @@ case "$SYSTEM" in
 	SYSTEM=$(resolve_device "$SYSTEM")
 	checkspace "$SYSTEM"
 
-	if [ "$BOOTED" ]; then
-		# TODO: add system update to queue
-		die "Cannot live replace system partition"
+	if mountpoint -q /android; then
+		echo "WARNING: Cannot live replace mounted system partition. Scheduled to process next boot..."
+		checkspace /var/gearlock
+		mv "$NEWIMG" /var/gearlock/system.img
+		add_gqueue sysup /var/gearlock/system.img
 	else
 		dd if="$NEWIMG" of="$SYSTEM" bs=1M status=progress
 		yes | fsck -fvy "$SYSTEM"
@@ -33,8 +32,9 @@ case "$SYSTEM" in
 	SYSTEM=$SRCDIR/system$COMP
 	checkspace
 
-	if [ "$BOOTED" ]; then
+	if mountpoint -q /android; then
 		mv -f "$SYSTEM" "$SYSTEM-pending_remove"
+		add_gqueue clean
 	else
 		rm -rf "$SYSTEM"
 	fi
