change output to stderr & api-like features

diff --git a/gearlock/usr/bin/system-update b/gearlock/usr/bin/system-update
--- a/gearlock/usr/bin/system-update
+++ b/gearlock/usr/bin/system-update
@@ -5,9 +5,9 @@ SIG=
 SYSIMAGE=
 UNMOUNT_LIST=
 
-die() { echo "==> ERROR: $*" && exit 1; }
+die() { echo "==> ERROR: $*" >&2 && exit "${2:-1}"; }
 
-[ "$4" ] && die "Invalid arguments '$*'"
+[ "$4" ] && die "Invalid arguments '$*'" 2
 
 while [ "$1" ]; do
 	case "$1" in
@@ -25,12 +25,12 @@ while [ "$1" ]; do
 	shift
 done
 
-[ -f "$SYSIMAGE" ] || die "Invalid system image '$SYSIMAGE'"
+[ -f "$SYSIMAGE" ] || die "Invalid system image '$SYSIMAGE' !" 3
 
 [ "$SIG" ] || SIG="$SYSIMAGE.sig"
 
 if [ -f "$SIG" ]; then
-	"$GEARLIB"/checksum "$SIG" "$SYSIMAGE" || die "Invalid Signature '$SIG'"
+	"$GEARLIB"/checksum "$SIG" "$SYSIMAGE" || die "Invalid Signature '$SIG' !"
 else
 	read -rn 1 -p "No Signature given. Continue? [y/n]: " confirm
 	[ "$confirm" = y ] || exit
@@ -46,8 +46,12 @@ esac
 
 while :; do
 
-	SYSIMAGE=$("$GEARLIB"/sysup/convert "$SYSIMAGE") ||
-		die "Not enough space to extract/compress '$SYSIMAGE'"
+	SYSIMAGE=$("$GEARLIB"/sysup/convert "$SYSIMAGE")
+	case "$?" in
+		1) die "Extract/Compress '$SYSIMAGE' failed !" 4;;
+		2) die "Cancelled extracting/compressing '$SYSIMAGE' !" 5;;
+		*) die "Not enough space to extract/compress '$SYSIMAGE' !" 6;;
+	esac
 
 	[ "$patched" ] ||
 		"$GEARLIB"/sysup/reinstall_patch "$SYSIMAGE" &&
@@ -62,7 +66,11 @@ while :; do
 	export SYSTEM_TYPE
 done
 
-SYSUP_STATUS=$("$GEARLIB"/sysup/"sysup_$MODE" "$SYSIMAGE")
-[ $? = 0 ] || die "$SYSUP_STATUS"
+SYSUP_STATUS=$("$GEARLIB/sysup/sysup_$MODE" "$SYSIMAGE")
+
+if [ $? != 0 ]; then
+	[ "$UNMOUNT_LIST" ] && umount -l $UNMOUNT_LIST
+	die "Apply update from '$SYSIMAGE' failed !" 7
+fi
 
 [ "$UNMOUNT_LIST" ] && umount -l $UNMOUNT_LIST
