added a-only system update

diff --git a/src/usr/bin/abswitch b/src/usr/bin/abswitch
--- a/src/usr/bin/abswitch
+++ b/src/usr/bin/abswitch
@@ -1,13 +1,20 @@
 #!/bin/bash
 
-. /etc/gearlock.conf
-
-OLD_MODE=$(/usr/lib/gearlock/abswitch/current)
+OLD_MODE=$(/usr/lib/gearlock/sysup/checkab)
 MODE=
 
 die() { echo "==> ERROR: $*" && exit 1; }
 
-[ "$2" ] && die "Invalid argument $*. Only ONE argument --ab or --aonly is allowed"
+set -- $(cat /proc/cmdline)
+for arg in "$@"; do case "$arg" in SYSTEM=*) SYSTEM="${arg#*=}" ;; esac done
+
+case "$SYSTEM" in
+/dev/* | LABEL=* | PARTLABEL=* | UUID=* | PARTUUID=*)
+  die "This script does not work on partition based system"
+  ;;
+esac
+
+[ "$2" ] && die "Invalid argument '$*'. Only ONE argument --ab or --aonly is allowed"
 
 case $1 in
 -a | --aonly) : aonly ;;
@@ -16,22 +23,30 @@ case $1 in
 esac
 MODE=$_
 
-[ "$MODE" = "$OLD_MODE" ] && die "Your current system has already been $MODE"
+[ "$MODE" = "$OLD_MODE" ] && [ "$MODE" = aonly ] &&
+  die "Your current system has already been '$MODE'"
 
 SYSTEM=
 COMP=
-
-set -- $(cat /proc/cmdline)
-for arg in "$@"; do case "$arg" in SYSTEM=*) SYSTEM="${arg#SYSTEM=}" ;; esac done
 
 case "$SYSTEM" in *.?fs | .img) COMP=".${SYSTEM##*.}" ;; esac
 
 case "$MODE" in
 ab)
-  mv -r "$SRCDIR/$SYSTEM" "$SRCDIR/system_a$COMP"
+  if [ "$OLD_MODE" = ab ]; then
+    to() { mv -r "$SRCDIR/$SYSTEM" "$SRCDIR/${SYSTEM//_$1/_$2}"; }
+    if echo "$SYSTEM" | grep -E '_a(\.(img|[se]fs))?$'; then
+      to a b
+    else
+      to b a
+    fi
+  else
+    mv -r "$SRCDIR/$SYSTEM" "$SRCDIR/system_a$COMP"
+  fi
   ;;
 aonly)
-  mv -r "$SRCDIR/$SYSTEM" "$SRCDIR/system$COMP"
+  mv -r "$SRCDIR/$SYSTEM" "$SRCDIR/system$COMP" &&
   rm -rf "$SRCDIR"/system_*
   ;;
 esac
+[ $? = 0 ] || die "Failed to switch '$MODE'"
diff --git a/src/usr/bin/system-update b/src/usr/bin/system-update
--- a/src/usr/bin/system-update
+++ b/src/usr/bin/system-update
@@ -1,1 +1,37 @@
 #!/bin/bash
+
+MODE=$(/usr/lib/gearlock/sysup/checkab)
+SIG=
+SYSIMAGE=
+
+die() { echo "==> ERROR: $*" && exit 1; }
+
+[ "$4" ] && die "Invalid arguments '$*'"
+
+while [ "$1" ]; do
+  case "$1" in
+  -s | --sig)
+    [ "$2" ] || die "Signature not given"
+    SIG=$2
+    shift
+    ;;
+  -s=* | --sig=*) SIG=${1#*=} ;;
+  *) SYSIMAGE=$1 ;;
+  esac
+  shift
+done
+
+[ "$SYSIMAGE" ] || die "No system image given"
+
+if [ "$SIG" ]; then
+  /usr/lib/gearlock/checksum "$SIG" || die "Invalid Signature '$SIG'"
+else
+  read -rn 1 -p "No Signature given. Continue? [y/n]: " confirm
+  [ "$confirm" = y ] || exit
+fi
+
+/usr/lib/gearlock/sysup/reinstall_patch "$SYSIMAGE" || die "Failed to patch new system image"
+
+SYSUP_STATUS=$(/usr/lib/gearlock/sysup/"sysup_$MODE" "$SYSIMAGE")
+[ $? = 0 ] || die "$SYSUP_STATUS"
+
