added abswitch

diff --git a/src/usr/bin/abswitch b/src/usr/bin/abswitch
--- a/src/usr/bin/abswitch
+++ b/src/usr/bin/abswitch
@@ -1,1 +1,43 @@
 #!/bin/bash
+
+. /etc/gearlock.conf
+
+OLD_MODE=
+MODE=
+
+if ls "$SRCDIR"/system_* | grep -E '_[ab](\.(img|[se]fs))?$'; then
+  OLD_MODE=ab
+else
+  OLD_MODE=aonly
+fi
+
+die() { echo "==> ERROR: $*" && exit 1; }
+
+[ "$2" ] && die "Invalid argument $*. Only ONE argument --ab or --aonly is allowed"
+
+case $1 in
+-a | --aonly) : aonly ;;
+-b | --ab) : ab ;;
+*) die "You must select --ab or --aonly to switch" ;;
+esac
+MODE=$_
+
+[ "$MODE" = $OLD_MODE ] && die "Your current system has already been $MODE"
+
+SYSTEM=
+COMP=
+
+set -- $(cat /proc/cmdline)
+for arg in "$@"; do case "$arg" in SYSTEM=*) SYSTEM="${arg#SYSTEM=}" ;; esac done
+
+case "$SYSTEM" in *.?fs | .img) COMP=".${SYSTEM##*.}" ;; esac
+
+case "$MODE" in
+ab)
+  mv -r "$SRCDIR/$SYSTEM" "$SRCDIR/system_a$COMP"
+  ;;
+aonly)
+  mv -r "$SRCDIR/$SYSTEM" "$SRCDIR/system$COMP"
+  rm -rf "$SRCDIR"/system_*
+  ;;
+esac
