gxp install

diff --git a/src/usr/bin/system-update b/src/usr/bin/system-update
--- a/src/usr/bin/system-update
+++ b/src/usr/bin/system-update
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-MODE=$(/usr/lib/gearlock/sysup/checkab)
+MODE=$("$GEARLIB"/sysup/checkab)
 SIG=
 SYSIMAGE=
 UNMOUNT_LIST=
@@ -25,22 +25,24 @@ while [ "$1" ]; do
 	shift
 done
 
-[ "$SYSIMAGE" ] || die "No system image given"
+[ -f "$SYSIMAGE" ] || die "Invalid system image '$SYSIMAGE'"
 
-if [ "$SIG" ]; then
-	/usr/lib/gearlock/checksum "$SIG" || die "Invalid Signature '$SIG'"
+[ "$SIG" ] || SIG="$SYSIMAGE.sig"
+
+if [ -f "$SIG" ]; then
+	"$GEARLIB"/checksum "$SIG" "$SYSIMAGE" || die "Invalid Signature '$SIG'"
 else
 	read -rn 1 -p "No Signature given. Continue? [y/n]: " confirm
 	[ "$confirm" = y ] || exit
 fi
 
-SYSIMAGE=$(/usr/lib/gearlock/sysup/convert "$SYSIMAGE") ||
+SYSIMAGE=$("$GEARLIB"/sysup/convert "$SYSIMAGE") ||
 	die "Not enough space to extract/compress '$SYSIMAGE'"
 
-/usr/lib/gearlock/sysup/reinstall_patch "$SYSIMAGE" ||
+"$GEARLIB"/sysup/reinstall_patch "$SYSIMAGE" ||
 	die "Failed to patch '$SYSIMAGE'"
 
-SYSUP_STATUS=$(/usr/lib/gearlock/sysup/"sysup_$MODE" "$SYSIMAGE")
+SYSUP_STATUS=$("$GEARLIB"/sysup/"sysup_$MODE" "$SYSIMAGE")
 [ $? = 0 ] || die "$SYSUP_STATUS"
 
 [ "$UNMOUNT_LIST" ] && umount -l $UNMOUNT_LIST
