change mount mechanism

diff --git a/gearlock/usr/lib/gearlock/compat/gearlockgxp/convert b/gearlock/usr/lib/gearlock/compat/gearlockgxp/convert
--- a/gearlock/usr/lib/gearlock/compat/gearlockgxp/convert
+++ b/gearlock/usr/lib/gearlock/compat/gearlockgxp/convert
@@ -7,60 +7,60 @@ SECRET_KEY='2Xj^7pAz=UN#5%=#%XQAFY-tik^jh97sz6C&2x8-dH+xPjhoz#BzP5**uk+7XH7w'
 die() { echo "==> ERROR: $1" >&2 && quit "${2:-1}"; }
 
 quit() {
-  rm -rf "$TMPDIR"
-  exit "$1"
+	rm -rf "$TMPDIR"
+	exit "$1"
 }
 
 usage() {
-  echo
+	echo
 }
 
 while getopts "adpvh" opt; do
-  case "$opt" in
-  # A) ARCH="$OPTARG" ;;
-  a) : "APKBUILD" ;;
-  d) : "DEBIAN" ;;
-  p) : "PKGBUILD" ;;
-  v) : "XBPS" ;;
-  h) usage && exit ;;
-  *) usage && exit 1 ;;
-  esac
-  TYPE=$_
+	case "$opt" in
+	# A) ARCH="$OPTARG" ;;
+	a) : "APKBUILD" ;;
+	d) : "DEBIAN" ;;
+	p) : "PKGBUILD" ;;
+	v) : "XBPS" ;;
+	h) usage && exit ;;
+	*) usage && exit 1 ;;
+	esac
+	TYPE=$_
 done
 shift $((OPTIND - 1))
 
 FILE=$1
 
 if [ ! "$TYPE" ]; then
-  for cmd in pacman xbps-src dpkg apk; do
-    command -v $cmd || continue
-    case "$cmd" in
-    pacman) : "PKGBUILD" ;;
-    xbps-src) : "XBPS" ;;
-    dpkg) : "DEBIAN" ;;
-    apk) : "APKBUILD" ;;
-    esac
-    TYPE=$_
-    break
-  done
+	for cmd in pacman xbps-src dpkg apk; do
+		command -v $cmd || continue
+		case "$cmd" in
+		pacman) : "PKGBUILD" ;;
+		xbps-src) : "XBPS" ;;
+		dpkg) : "DEBIAN" ;;
+		apk) : "APKBUILD" ;;
+		esac
+		TYPE=$_
+		break
+	done
 fi
 
 CONTENT=$("$TOOLCHAIN"/bin/garca l -p"$SECRET_KEY" "$FILE")
 
 TMPDIR=$("$GEARLIB"/checkfree "$(
-  printf "%s" "$CONTENT" | tail -1 | awk '{print $3}'
+	printf "%s" "$CONTENT" | tail -1 | awk '{print $3}'
 )") ||
-  die "Not enough space to perform this action" 1
+	die "Not enough space to perform this action" 1
 
 # check for !zygotee.sh
 
 printf "%s" "$CONTENT" | grep '!zygote.sh' ||
-  die "'$FILE' is either corrupted or not supported ..." 2
+	die "'$FILE' is either corrupted or not supported ..." 2
 
 CURRENT_DIR=$(pwd)
 
 "$TOOLCHAIN"/bin/garca -o"$TMPDIR" -p"$SECRET_KEY" "$FILE" ||
-  die "Failed to extract '$FILE'" 3
+	die "Failed to extract '$FILE'" 3
 
 cd "$TMPDIR"
 chmod +x '!zygote.sh'
@@ -79,8 +79,8 @@ VERSION=${VERSION:-"1.0"} # default value
 SHORTDESC=${SHORTDESC#"Bakes you a cake @_@"}
 
 reattr() {
-  [ -e "$2" ] || return
-  xargs -L1 $(eval echo "$1") <"$2" >/dev/null 2>&1
+	[ -e "$2" ] || return
+	xargs -L1 $(eval echo "$1") <"$2" >/dev/null 2>&1
 }
 
 reattr "chmod" '.!zygote/mode'
@@ -92,37 +92,60 @@ reattr "ln -srf" '.!zygote/link'
 #	  if /system/lib/firmware exists, make a split firmware package
 #	  or else make it a flashable zip
 # if /gearlock exists, make boot hook
-#
+
+bindpkg() {
+	TYPE=$1
+	mkdir -p "usr/lib/$TYPE"
+	cp -a "system/lib/$TYPE" "$TMPDIR/$(dirname "usr/lib/$TYPE")/$(basename "$TYPE")"
+
+	case "$TYPE" in
+	modules/*) for kernel in "$@"; do
+		shift
+		[ -f "$kernel" ] && cp "$kernel" "$TMPDIR/usr/lib/$1/kernel" && break
+	done ;;
+	esac
+
+	MAKEFILE="
+build:
+	echo 'Creating package...'
+
+install:
+	cp -a /usr \$(DESTDIR)/
+"
+}
 
 if [ -d system ]; then
-  if [ -d system/lib/modules ]; then
-    kernel=$(basename ./system/lib/modules/*)
-    "$GEARLIB"/makepkg/bindpkg \
-      modules/"$kernel" \
-      "kernel-su" "kernel" \
-      -A "$ARCH" \
-      -D "${SHORTDESC:-"Linux kernel $kernel - GearLock GXP package by $AUTHOR"}" \
-      -l "GPL2" \
-      -M "$AUTHOR" \
-      -N "linux-$kernel" \
-      -O "$TMPDIR" \
-      -v "${kernel%-*}" &&
-      rm -rf system/lib/modules/*
-  fi
-  if [ -d system/lib/firmware ]; then
-    "$GEARLIB"/makepkg/bindpkg \
-      firmware \
-      -A "$ARCH" \
-      -D "${SHORTDESC:-"Linux firmware - GearLock GXP package by $AUTHOR"}" \
-      -l "GPL2 GPL3 custom" \
-      -M "$AUTHOR" \
-      -N "linux-firmware" \
-      -O "$TMPDIR" \
-      -v "$(printf "%s" "$CONTENT" | grep -E "system/lib/firmware$" | sed 's/^([0-9]{4})-([0-9]{2})-([0-9]{2}).*/\1\2\3/g')" &&
-      rm -rf system/lib/firmware
-  fi
+	if [ -d system/lib/modules ]; then
+		kernel=$(basename ./system/lib/modules/*)
+		move() { bindpkg modules/"$kernel" "kernel-su" "kernel"; }
+		"$GEARLIB"/makepkg/genbuild \
+			-A "$ARCH" \
+			-D "${SHORTDESC:-"Linux kernel $kernel - GearLock GXP package by $AUTHOR"}" \
+			-l "GPL2" \
+			-M "$AUTHOR" \
+			-N "linux-$kernel" \
+			-O "$TMPDIR" \
+			-v "${kernel%-*}" \
+			-S "$(du -sk system/lib/modules | awk '{print $1}')" \
+			-B "$MAKEFILE" &&
+			rm -rf system/lib/modules/*
+	fi
+	if [ -d system/lib/firmware ]; then
+		move() { bindpkg firmware; }
+		"$GEARLIB"/makepkg/genbuild \
+			-A "$ARCH" \
+			-D "${SHORTDESC:-"Linux firmware - GearLock GXP package by $AUTHOR"}" \
+			-l "GPL2 GPL3 custom" \
+			-M "$AUTHOR" \
+			-N "linux-firmware" \
+			-O "$TMPDIR" \
+			-v "$(printf "%s" "$CONTENT" | grep -E "system/lib/firmware$" | sed 's/^([0-9]{4})-([0-9]{2})-([0-9]{2}).*/\1\2\3/g')" \
+			-S "$(du -sk system/lib/firmware | awk '{print $1}')" \
+			-B "$MAKEFILE" &&
+			rm -rf system/lib/firmware
+	fi
 
-  # convert to zip
+	# convert to zip
 fi
 
 # TODO: make boot hooks
diff --git a/gearlock/usr/lib/gearlock/makepkg/genbuild b/gearlock/usr/lib/gearlock/makepkg/genbuild
--- a/gearlock/usr/lib/gearlock/makepkg/genbuild
+++ b/gearlock/usr/lib/gearlock/makepkg/genbuild
@@ -1,16 +1,24 @@
 #!/bin/bash
 
+die() { echo "==> ERROR: $TYPE" >&2 && quit "${2:-1}"; }
+
+quit() {
+	rm -rf "$TMPDIR"
+	exit "$?"
+}
+
 usage() {
 	echo
 }
 
-while getopts "A:D:d:hI:l:M:m:O:o:P:p:r:u:v:t:" opt; do
+while getopts "A:B:D:d:hI:l:M:m:o:P:p:r:S:u:v:t:" opt; do
 	case "$opt" in
 	A) ARCH="$OPTARG" ;;
+	B) MAKEFILE="$OPTARG" ;;
 	D) DESC="$OPTARG" ;;
 	I) NAME=$OPTARG ;;
 	M) MAINTAINER="$OPTARG" ;;
-	O) OUT=$OPTARG ;;
+	# O) OUT=$OPTARG ;;
 	P) PROVIDE_PRIOR="$OPTARG" ;;
 	d) DEPENDS="${OPTARG//,/ }" ;;
 	h) usage && exit ;;
@@ -19,9 +27,10 @@ while getopts "A:D:d:hI:l:M:m:O:o:P:p:r:u:v:t:" opt; do
 	o) OPTS=$OPTARG ;;
 	p) PROVIDES="${OPTARG//,/ }" ;;
 	r) REL=$OPTARG ;;
+	S) NEEDED_SPACE=$((OPTARG * 2)) ;;
 	u) URL=$OPTARG ;;
 	v) VER=$OPTARG ;;
-	t) TYPE="$OPTARG" ;;
+	t) PKGTYPE="$OPTARG" ;;
 	*) usage && exit 1 ;;
 	esac
 done
@@ -31,27 +40,23 @@ for arg in "$NAME" "$ARCH" "$MAINTAINER"; do
 	[ "$arg" ] || exit 1
 done
 
-if [ ! "$TYPE" ]; then
-	for cmd in pacman xbps-src dpkg apk; do
-		command -v $cmd || continue
-		case "$cmd" in
-		pacman) : "PKGBUILD" ;;
-		xbps-src) : "XBPS" ;;
-		dpkg) : "DEBIAN" ;;
-		apk) : "APKBUILD" ;;
-		esac
-		TYPE=$_
-		break
-	done
-fi
-
+PKGTYPE=${PKGTYPE:-"$OSPKGPKGTYPE"}
 VER=${VER:-"0.0.1"}
 REL=${REL:-"0"}
-OUT=${OUT:-"/dev/stdout"}
+# OUT=${OUT:-"/dev/stdout"}
 
-case "$TYPE" in
+TMPDIR=$("$GEARLIB"/checkfree "$NEEDED_SPACE") ||
+	die "Not enough space to perform this action" 1
+
+CURRENT_DIR=$(pwd)
+
+move
+
+cd "$TMPDIR"
+
+case "$PKGTYPE" in
 PKGBUILD | APKBUILD)
-	cat <<EOF >>"$OUT/${TYPE,,}"
+	cat <<EOF >>"${PKGTYPE}"
 # Generated by Gearlock genbuild
 # Maintainer: $MAINTAINER
 
@@ -79,12 +84,13 @@ package() {
 EOF
 	;;
 XBPS)
-	cat <<EOF >>"$OUT/template"
+	cat <<EOF >>"template"
 # Generated by Gearlock genbuild
 
 maintainer='$MAINTAINER'
 pkgname=$NAME
-pkgver=$VER
+version=$VER
+archs="$ARCH"
 revision=$REL
 short_desc="$DESC"
 ${URL:+"homepage=\"$URL\""}
@@ -92,8 +98,9 @@ license="$LICENSE"
 ${DEPENDS:+"depends=\"$DEPENDS\""}
 ${MAKEDEPENDS:+"makedepends=\"$MAKEDEPENDS\""}
 
-
-make VERSION=\$pkgver-\$revision
+do_build() {
+	make VERSION=\$pkgver-\$revision
+}
 
 do_install() {
 	make install DESTDIR="\$DESTDIR"
@@ -104,3 +111,18 @@ EOF
 DEBIAN) ;;
 *) ;;
 esac
+
+printf "%s" "$MAKEFILE" >Makefile
+
+case "$PKGTYPE" in
+APKBUILD) abuild -Frf && apk add /root/packages/*/*/"$NAME-$VER-r$REL.apk" ;;
+PKGBUILD) makepkg -sif ;;
+XBPS) xbps-src pkg "$NAME" && do_something ;; #
+DEBIAN) dpkg-buildpackage && dpkg -i ;; #
+*) ;;
+esac ||
+	die "Build package failed" 2
+
+cd "$CURRENT_DIR"
+
+rm -rf "$TMPDIR"
